services:
  laboratorio.app:
    build:
      context: ./docker/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
        MYSQL_CLIENT: mariadb-client
    container_name: laboratorio.app
    image: sail-8.3/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
      - '${REVERB_SERVER_PORT:-8080}:8080'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      PHP_CLI_SERVER_WORKERS: 5
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
networks:
  default:
    external: true
    name: proxygratis
