-- Inserción de todos los cargos en una sola sentencia INSERT
INSERT INTO cargos (nombre) VALUES
    ('Director General'),
    ('Subdirector Médico'),
    ('Subdirector Administrativo'),
    ('Jefe de Enfermería'),
    ('Médico Especialista'),
    ('Médico General'),
    ('Enfermero(a) Jefe'),
    ('Enfermero(a) General'),
    ('Auxiliar de Enfermería'),
    ('Fisioterapeuta'),
    ('Nutricionista'),
    ('Farmacéutico'),
    ('Técnico de Laboratorio'),
    ('Técnico en Radiología'),
    ('Recepcionista'),
    ('Administrador de Hospital'),
    ('Contador'),
    ('Técnico de Mantenimiento'),
    ('Personal de Limpieza'),
    ('Guardia de Seguridad'),
    ('Técnico en Sistemas'),
    ('Trabajador Social'),
    ('Psicólogo'),
    ('Secretaria'),
    ('Auxiliar Administrativo'),
    ('Cocinero'),
    ('Camillero'),
    ('Especialista en Recursos Humanos'),
    ('Personal de Servicios Generales'),
    ('Asistente Dental'),
    ('Terapeuta Ocupacional'),
    ('Auditor Médico'),
    ('Gerente de Calidad'),
    ('Coordinador de Capacitación');
