INSERT INTO `encuestas` (`id`, `nombre`) VALUES
(1, 'INSTRUMENTO DE SUPERVISIÓN INTEGRAL');

INSERT INTO `grupos` (`id`, `nodo`, `nombre`, `parent_id`) VALUES
	(1, '1', 'COMPONENTE: GESTIÓN', NULL),
	(2, '1.1', 'GESTION', 1),
	(12, '1.2', 'Recursos Humanos', 1),
	(17, '1.3', 'GESTION DE LA CALIDAD y SEGURIDAD DEL PACIENTE', 1),
	(22, '1.4', 'Sistema de Información y Tecnología de la Información', 1),
	(25, '2', 'INFRAESTRUCTURA Y EQUIPAMIENTO - LOGISTICA', NULL),
	(26, '2.1', 'INFRAESTRUCTURA', 25),
	(29, '2.2', 'EQUIPAMIENTO', 25),
	(33, '2.3', 'LOGISTICA', 25),
	(37, '3', 'ORGANIZACIÓN', NULL),
	(38, '3.1', 'REFERENCIA  y CONTRAREFERENCIA', 37),
	(42, '3.2', 'EPIDEMIOLOGIA', 37),
	(46, '3.3', 'ADECUACION DE AMBIENTES', 37),
	(50, '4', 'PRESTACIÓN DE LOS SERVICIOS', NULL),
	(51, '4.1', 'ATENCION INTEGRAL DE SALUD DEL NIÑO (DIT)', 50),
	(57, '4.2', 'ATENCION INTEGRAL DEL ADOLESCENTE', 50),
	(62, '4.3', 'ATENCION INTEGRAL JOVEN', 50),
	(65, '4.4', 'Atención Integral de Salud del Adulto', 50),
	(69, '4.5', 'ATENCION INTEGRAL DEL ADULTO MAYOR', 50),
	(74, '4.6', 'ES. SALUD SEXUAL Y REPRODUCTIVA', 50),
	(82, '4.7', 'ES.  TBC', 50),
	(87, '4.8', 'ES. ENFERMEDADES METAXEMICAS', 50),
	(92, '4.9', 'ES. PCITS-VIH/SIDA', 50),
	(97, '4.10', 'PROGRAMA ESTRATEGICO DE  PREVENCION DE CANCER', 50),
	(101, '4.11', 'ES. NUTRICIONAL', 50),
	(106, '4.12', 'ES. SALUD BUCAL', 50),
	(111, '4.13', 'ES. SALUD MENTAL', 50),
	(116, '4.14', 'ES. DAÑOS No TRANSMISIBLES', 50),
	(120, '4.15', 'ES. SALUD OCULAR Y PREVENCIÓN DE LA CEGUERA', 50),
	(124, '4.16', 'PREVENCION Y CONTROL DE ZOONOSIS', 50),
	(129, '4.17', 'SALUD AMBIENTAL', 50),
	(135, '4.18', 'VIGILANCIA DE CALIDAD DE MANEJO DE RESIDUOS SOLIDOS PELIGROSOS', 50),
	(141, '4.19', 'ESTRATEGIA SANITARIA SALUD FAMILIAR', 50),
	(148, '4.20', 'PROMOCIÓN DE LA SALUD', 50),
	(154, '4.21', 'SEGUROS', 50),
	(160, '4.22', 'GESTIÓN DE RIESGOS DE DESASTRES - GRD', 50),
	(167, '4.23', 'SISMED', 50),
	(173, '4.24', 'TELEMEDICINA', 50),
	(177, '4.25', 'LABORATORIO', 50),
	(189, '4.26', 'COMUNICACIONES', 50);

INSERT INTO `preguntas` (`id`, `nombre`, `nodo`, `verificar`, `tipo`, `encuesta_id`, `grupo_id`) VALUES
	(3, 'La IPRESS cuenta con equipo de gestión formalmente constituido y tiene asignado sus funciones.', '1.1.1', NULL, 'Simple', 1, 2),
	(4, 'El EESS Cuenta con resolución de  categorización vigente.', '1.1.2', NULL, 'Simple', 1, 2),
	(5, 'El Jefe del EESS monitorea y evalúa el cumplimiento de sus indicadores y Plan Anual de Trabajo con participación del personal del EESS.', '1.1.3', NULL, 'Multiple', 1, 2),
	(6, 'El EESS  tiene acceso a información básica de los servicios de salud que se ofertan', '1.1.4', NULL, NULL, 1, 2),
	(7, 'El EESS  tiene acceso a información básica de los servicios de salud que se ofertan', '1.1.5', NULL, NULL, 1, 2),
	(8, 'El EESS muestra externamente buena imagen institucional', '1.1.5', NULL, NULL, 1, 2),
	(9, 'Tiene sala situacional actualizada por trimestre, avance indicadores sanitarios', '1.1.6', NULL, NULL, 1, 2),
	(10, 'El EESS cuenta  con equipos deteriorados ( oxidados , rotos) con expediente para el recojo DIRIS', '1.1.7', NULL, NULL, 1, 2),
	(11, 'Cuenta con mapa de sectorizaciónsegun GEORIS  con nominacion de los responsable.', '1.1.5', NULL, NULL, 1, 2),
	(13, 'Identifica necesidades de capacitación del RRHH', '1.2.1', NULL, NULL, 1, 12),
	(14, 'El establecimiento realiza la programacion de turnos y actividades de acuerdo a normatividad y prioridad sanitaria', '1.2.2', NULL, NULL, 1, 12),
	(15, 'El establecimiento realiza control de Asistencia y Permanencia de los RRHH', '1.2.3', NULL, NULL, 1, 12),
	(16, 'Registro de Recursos Humanos con que cuenta el EESS', '1.2.4', NULL, NULL, 1, 12),
	(18, 'El establecimiento cuenta con mecanismos de escucha al usuario que permite recoger las sugerencias,  reclamos de los usuarios externos, así como verificar la permanente evaluación y solución de los mismos.', '1.3.1', NULL, NULL, 1, 17),
	(19, 'Cuenta con Plan de Gestión de la Calidad aprobado por Direcciòn o su equivalente  y se ejecuta de acuerdo a lo programado', '1.3.2', NULL, NULL, 1, 17),
	(20, 'El Establecimeinto de salud ha realizado el proceso de autoevaluación para la acreditación de los servicios de salud con una antigüedad no mayor a un año', '1.3.3', NULL, NULL, 1, 17),
	(21, 'Se evidencia la existencia de acciones o proyectos de mejora continua de la calidad basados en el análisis de los resultados de las mediciones  de calidad realizadas', '1.3.4', NULL, NULL, 1, 17),
	(23, 'La operatividad de los sistemas de comunicación y herramientas informáticas son adecuadas.', '1.4.1', NULL, NULL, 1, 22),
	(24, 'El personal del establecimiento realiza el registro,digitacion  de la prestación de manera adecuada', '1.4.2', NULL, NULL, 1, 22),
	(27, 'El EESS cuenta con título de propiedad y está saneado legalmente', '2.1.1', NULL, NULL, 1, 26),
	(28, 'Cuenta con el Plan de Mantenimiento  de la Infraestructura 2023  presentado a la RIS', '2.1.2', NULL, NULL, 1, 26),
	(30, 'El Almacén cuenta con Kardex actualizado de equipos e insumos', '2.2.1', NULL, NULL, 1, 29),
	(31, 'El Almacén  guarda las medidas de bioseguridad para su conservación', '2.2.2', NULL, NULL, 1, 29),
	(32, 'Cuenta con el Plan de mantenimiento preventivo y correctivo de los equipos biomédico y este se encuentra en ejecución', '2.2.3', NULL, NULL, 1, 29),
	(34, 'Cuenta con el area de almacen ordenado, con Kardex al día, el material eductivo comunicacional esta ordenado de acuerdo a la estrategias saniataria', '2.3.1', NULL, NULL, 1, 33),
	(35, 'El personal de vigilancia ha sido capacitado  en las estrategias sanitarias,  y  conoce los deberes y derechos del usuario', '2.3.2', NULL, NULL, 1, 33),
	(36, 'Se ha gestionado ante la DIRIS la baja de los equipos inopertivos y recojo de inservibles', '2.3.3', NULL, NULL, 1, 33),
	(39, 'Existe un responsable de  las referncias el cual cumple con el monitoreo de citadas, aceptadas y  levanta posibles observaciones, reporta  al inmediato superior diariamente', '3.1.1', NULL, NULL, 1, 38),
	(40, 'Contabiliza  las referencias en el sistema REFCOM  y comunica la aceptacion de la referencia a la usuaria.', '3.1.2', NULL, NULL, 1, 38),
	(41, 'Cuenta con equipos de computacion e internet operativo , luz', '3.1.3', NULL, NULL, 1, 38),
	(43, 'Cuenta con personal capacitado en los últimos dos años para la Notificación Inmediata (Dengue, Rubeola, PFA, Malaria, Influenza, Tos Ferina, etc.)', '3.2.1', NULL, NULL, 1, 42),
	(44, 'Las alertas epidemiología   ha sido motivo de Reunión de capacitación a todo el personal de salud a cargo del médico Jefe', '3.2.2', NULL, NULL, 1, 42),
	(45, 'La IPRESS reporta oportunamente casos de notificación epidemiológica', '3.2.3', NULL, NULL, 1, 42),
	(47, 'El EEESS dispone de un consultorio de atención único  (s) Niño para brindar el paquete de atencion integral ( Inmunización , CRED, dosaje de hemoglobina  )', '3.3.1', NULL, NULL, 1, 46),
	(48, 'El EESS cuenta con equipamiento para el traslado interno de los pacientes de riesgo (silla de ruedas ,camillas con ruedas , entre otros )', '3.3.2', NULL, NULL, 1, 46),
	(49, 'Dispone de rampa y letreros para la atención preferencial', '3.3.3', NULL, NULL, 1, 46),
	(52, 'Cuenta con los siguientes documentos normativos y ha socializado :                                                                                              1)NTS N° 196-MINSA7DGIESP-2022 " Esquema de Vacunación                                                                                               2)Directiva Sanitaria N° 054- MINSA/DGE-V01 para la vigilancia epidemiológica de Eventos supuestamente atribuidos a la vacunación,                                                                                   3)NTS 136-minsa/2017/DGIESP: Norma Técnica de Salud para el manejo de la cadena de frio de inmunizaciones "                                                                                            4)NTS N° 137-MINSA/2017/DGIESP Norma Técnica de Salud para el crecimiento y Desarrollo de la niña y del niño menores de 5 años.', '4.1.1', NULL, NULL, 1, 51),
	(53, 'Cuenta con  la  programación paquete niño  del 2023.', '4.1.2', NULL, NULL, 1, 51),
	(54, 'Cuenta con registro de seguimiento de los niños identificados a travéz del aplicativo gestión de indicadores.com (RN, niño menor de 4 años)', '4.1.3', NULL, NULL, 1, 51),
	(55, 'Cuenta con consultorio de atencion adecuado , para brindar el paquete integrado de e servicios : CRED, vacunas, dosaje de hemoglobina y suplementación de hierro', '4.1.4', NULL, NULL, 1, 51),
	(56, 'Realiza el seguimiento de niños menores de 2 año con primera y segunda dosis  de SPR', '4.1.5', NULL, NULL, 1, 51),
	(58, 'Cuenta con documento normativo Etapa de Vida Adolescente y lo ha socializado al equipo de trabajo 2023', '4.2.1', NULL, NULL, 1, 57),
	(59, 'Cuenta con Análisis situacional de salud del adolescente actualizado por trimestre', '4.2.2', NULL, NULL, 1, 57),
	(60, 'Cuenta con consultorio diferenciado y materiales, equipos e insumos para la atencion integral del adolescente.', '4.2.3', NULL, NULL, 1, 57),
	(61, 'Cuenta con líderes o educadores pares.', '4.2.4', NULL, NULL, 1, 57),
	(63, 'Responsable y Equipo Multidisciplinario de la Etapa de Vida Adulto designado con documento.', '4.3.1', NULL, NULL, 1, 62),
	(64, 'Numero de paquetes de atencion integral ejecutado', '4.3.2', NULL, NULL, 1, 62),
	(66, 'Cuenta con Plan de trabajo presentado por  el responsable dominado con memorandum', '4.4.1', NULL, NULL, 1, 65),
	(67, 'Cuenta con Formatos de Atención Integral del Adulto.', '4.4.2', NULL, NULL, 1, 65),
	(68, 'Número de adultos con Plan de Atención Integral Ejecutado.', '4.4.3', NULL, NULL, 1, 65),
	(70, 'Cuenta con la Evaluación 2022 y la  programación metas 2023.', '4.5.1', NULL, NULL, 1, 69),
	(71, 'Aplica la Valoración clínica del adulto Mayor', '4.5.2', NULL, NULL, 1, 69),
	(72, 'Cuenta con los formatos de atencion Integral  del adulto Mayor.', '4.5.3', NULL, NULL, 1, 69),
	(73, 'El responsable socializa el fluxograma de atencion Integral del adulto Mayor', '4.5.4', NULL, NULL, 1, 69),
	(75, 'Cuenta con Programación anual 2023  y ejecuta las actividades', '4.6.1', NULL, NULL, 1, 74),
	(76, 'Cuenta con la relación de Gestantes con FPP y Monitoriza  el seguimiento de las gestantes y programación de plan de parto efectivo.(Radar de gestantes)', '4.6.2', NULL, NULL, 1, 74),
	(77, 'Cuenta con los equipos, insumos necesarios para el CPN', '4.6.3', NULL, NULL, 1, 74),
	(78, 'Cuenta con el cronograma de actividades extramurales: captación de gestantes en el primer trimestre.', '4.6.4', NULL, NULL, 1, 74),
	(79, 'Durante la atención de parto se utiliza el partograma', '4.6.5', NULL, NULL, 1, 74),
	(80, 'Cuenta con los equipos básicos para la atención materna y del RN', '4.6.6', NULL, NULL, 1, 74),
	(81, 'Se han implementado estrategias para incrementar la atencion de parto institucional y analiza resultados de la intervención.', '4.6.7', NULL, NULL, 1, 74),
	(83, 'Cuenta con la NTS N°200-2023-MINSA/DGIESP "Norma técnica de salud para el cuidado integral de la persona afectada por tuberculosis, familia y comunidad”.', '4.7.1', NULL, NULL, 1, 82),
	(84, 'El EESS  implementa acciones para  disminuir riesgo de abandono al tratamiento de tuberculosis.', '4.7.2', NULL, NULL, 1, 82),
	(85, 'El EESS implementa estrategias para el incremento de busqueda de sintomaticos respiratorios teniendo en cuenda definicion operativa de Sintomatico Respiratorio.', '4.7.3', NULL, NULL, 1, 82),
	(86, 'El servicio de laboratorio cuenta con responsable para el procesamineto de baciloscopias y dispone de los equipos e insumos para el procesamiento de baciloscopías.', '4.7.4', NULL, NULL, 1, 82),
	(88, 'Cuenta con:                                                                                                                                  -Guía de Práctica Clínica para la atención de casos de Dengue en el Perú,                                                                                                                                                              -Norma Sanitaria Nº125 - MINSA/ 2016 / CDC.INS.                                                                                         Norma técnica de salud para la vigilancia, epidemiologica y diagnóstico de laboratorio de Dengue, Chikungunya, Zik ,                                           -NT para la atencion integral de la persona afectada con leptospirosis,                                                                                                                -NT sobre Prevención y Tratamiento por animales ponzoñosos y ha sido socializada.', '4.8.1', NULL, NULL, 1, 87),
	(89, 'Cuenta con el Responsable de la estrategia y cuenta con el Plan de las actividades de Vigilancia y Control del Aedes Aegypti, según cronograma y Metas establecidas.', '4.8.2', NULL, NULL, 1, 87),
	(90, 'Mapa de riesgo actualizado de las localidades en escenario epidemiológico I y  II. Según Corresponda.', '4.8.3', NULL, NULL, 1, 87),
	(91, 'Realiza Capacitaciones, Charlas sobre la Prevención y Control del Aedes Aegypti en las instituciones de su jurisdicción correspondiente.', '4.8.4', NULL, NULL, 1, 87),
	(93, 'Cuenta con: NTS N°126-MINSA/2016/DGIESP, NTS 650-2009; NTS N°159-2023-MINSA/DGIESP, NT N°169, socializadas y  disponible para consulta', '4.9.1', NULL, NULL, 1, 92),
	(94, 'Reporte de casos positivos  en VIH, ITS segùn Formato  actualizado con reportes al corte de supervisión.', '4.9.2', NULL, NULL, 1, 92),
	(95, 'Cuenta con Personal responsable de la estrategia y responsable de la PTMI', '4.9.3', NULL, NULL, 1, 92),
	(96, 'Cuenta con el registro nominal de atención y seguimiento a la gestante/puérpera con VIH, Sifilis y Hepatitis y el niño expuesto al VIH.', '4.9.4', NULL, NULL, 1, 92),
	(98, 'La IPRESS cuenta con la programacion mensual  de intervenciones comunitarias para la prevencion del Cancer', '4.10.1', NULL, NULL, 1, 97),
	(99, 'Cuenta con los insumos necesarios para el tamizaje precoz de cáncer de cuello uterino y de colón .', '4.10.2', NULL, NULL, 1, 97),
	(100, 'Cuenta con el flujo de atencion para el tamizaje de cancer de colon , cuello,, piel. Prostata', '4.10.3', NULL, NULL, 1, 97),
	(102, 'Cuenta, difunde y socializa la Norma Técnica Sanitaria N°134-MINSA/2017/DGIESP Manejo Terapeutico y preventivo de la anemia en niños, adolescentes, gestantes y puerperas.)                                RM 229-2020 -MINSA que modifica el numeral 5.3', '4.11.1', NULL, NULL, 1, 101),
	(103, 'Cuenta con  mapa o gráfico de los problemas nutricionales priorizados (anemia o desnutrición) publicado en la sala situacional', '4.11.2', NULL, NULL, 1, 101),
	(104, 'Realiza actividades preventiva promocionales para la disminución y prevención de la anemia', '4.11.3', NULL, NULL, 1, 101),
	(105, 'Tiene base de datos accesible  de niños , gestantes y adolescentes con diagnóstico de anemia que llegan al EESS para el seguimiento.', '4.11.4', NULL, NULL, 1, 101),
	(107, 'Programación mensual de actividades extramuro', '4.12.1', NULL, NULL, 1, 106),
	(108, 'Cuenta con el flujo de atencion de niños  de 3 a 11 años  para la atencion odontologica ,gestantes,y adulto mayor para la atencion odontologica', '4.12.2', NULL, NULL, 1, 106),
	(109, 'Cuenta con Unidad dental operativa que incluye: compresora, lampara de luz led, pieza de mano, esterilizador en seco o autoclave', '4.12.3', NULL, NULL, 1, 106),
	(110, 'Cuenta con insumos necesarios para la atencion odontologica', '4.12.4', NULL, NULL, 1, 106),
	(112, 'Cuenta con Plan de Trabajo Anual  Salud Mental con sello de  VB recibido por la jefatura de su EESS', '4.13.1', NULL, NULL, 1, 111),
	(113, 'Articula y ejecuta  acciones en salud mental con organismos gubernamentales, no gubernamentales,organizaciones de base y actores sociales', '4.13.2', NULL, NULL, 1, 111),
	(114, 'Presenta analisis de la situacion de salud Mental por timestre de la zona de su jirdiaccion (Atendidos, Atenciones, etc…)', '4.13.3', NULL, NULL, 1, 111),
	(115, 'Expone de manera gráfica los indicadores de morbilidad periodicamente', '4.13.4', NULL, NULL, 1, 111),
	(117, 'Cuenta con padrón nominal de pacientes con  enfermedades crónicas no transmisibles con seguimiento', '4.14.1', NULL, NULL, 1, 116),
	(118, 'Cuenta con insumos necesarios para la atencion en la Estrategia Sanitaria de Prevención y Control de Daños No Transmisibles', '4.14.2', NULL, NULL, 1, 116),
	(119, 'Cuenta con las Normas , Guias de Practica Clinica, Manual HIS de la Estrategia Sanitaria de Prevención y Control de Daños No Transmisibles', '4.14.3', NULL, NULL, 1, 116),
	(121, 'Cuenta con el Responsable y  Plan de Trabajo de la Estrategia', '4.15.1', NULL, NULL, 1, 120),
	(122, 'Realiza actividades de prevención, promoción de errores refractivos y cataratas en instituciones educativas, clubes del adulto mayor, etc.', '4.15.2', NULL, NULL, 1, 120),
	(123, 'Cuenta con insumos y materiales para realizar el tamizaje de agudeza visual: oclusores para adultos y niños, cartilla de Snellen para iletrados y letrados, linterna, letra E.', '4.15.3', NULL, NULL, 1, 120),
	(125, 'Norma Tecnica N°131-MINSA /2017 Norma Tecnica para la vigilancia ,prevencion y control de la Rabia Huamna en el peru', '4.16.1', NULL, NULL, 1, 124),
	(126, 'Cuenta con mapa de riesgo actualizado de los casos presentados por Mordeduras por Animales.', '4.16.2', NULL, NULL, 1, 124),
	(127, 'Libro de Registro de personas en Vacunación Anirrábica y Actualizado.', '4.16.3', NULL, NULL, 1, 124),
	(128, 'El responsable ha brindado charla  sobre Rabia al personal de salud (medicos y otro personal de salud)', '4.16.4', NULL, NULL, 1, 124),
	(130, 'Cuenta con Personal responsable del área de salud ambiental y cuenta con plan de actividades de Salud Ambiental .', '4.17.1', NULL, NULL, 1, 129),
	(131, 'Tiene la programacion del control de calidad de agua de cobnsumo humano', '4.17.2', NULL, NULL, 1, 129),
	(132, 'Tiene la programacion de control y vigilancia de piscinas y playas saludables', '4.17.3', NULL, NULL, 1, 129),
	(133, 'Libro de Registro de denuncia por Mordeduras de Animales y Actualizado en función de los casos presentados.', '4.17.4', NULL, NULL, 1, 129),
	(134, 'Charlas sobre Tenencia Responsable de Animales de Compañía – 2023', '4.17.5', NULL, NULL, 1, 129),
	(136, 'Cuenta con un  Programa  sobre Manejo de Residuos Sólidos Peligrosos. Cuenta con N T S Nº 144 -MINSA/2018-DIGESA', '4.18.1', NULL, NULL, 1, 135),
	(137, 'Monitorea y  evalúa el Manejo y Recojo de los Residuos Sólidos   Peligrosos generados en los EE SS. Según Normatividad.', '4.18.2', NULL, NULL, 1, 135),
	(138, 'Cuenta con los materiales e inumos para el adecuado  Manejo de Residuos   Residuos Sólidos en Establecimientos de Salud,', '4.18.3', NULL, NULL, 1, 135),
	(139, 'Cuenta con personal de limpieza para una adecuada  desinferccion de los ambientes o servicios  del  EE SS. en el presente año.', '4.18.4', NULL, NULL, 1, 135),
	(140, 'El personal responsable gestiona y/o capacita al personal del EE SS  sobre Manejo de Residuos Sólidos de acuerdo a la  Norma técnica N° 144-2018 /MINSA en  el presente año', '4.18.5', NULL, NULL, 1, 135),
	(142, 'Cuenta con programación de salidas extramurales para realizar visitas de salud familiar', '4.19.1', NULL, NULL, 1, 141),
	(143, 'Cuenta con carpetas y fichas familiares', '4.19.2', NULL, NULL, 1, 141),
	(144, 'Identificacion y priorizacion de sectores vulnerables y cuenta con relacion de responsables del sector 2023', '4.19.3', NULL, NULL, 1, 141),
	(145, 'Conformación o participación con autoridades locales y actores sociales de la jurisdiccion para la intervencion con las familias', '4.19.4', NULL, NULL, 1, 141),
	(146, 'Registro de distribucion de familias al personal asistencial nombrado para visitas de salud familiar', '4.19.5', NULL, NULL, 1, 141),
	(147, 'Registro en el formato HIS  de las actividades de salud familiar', '4.19.6', NULL, NULL, 1, 141),
	(149, 'Cuenta con documento oficial de Responsable de Promoción de la Salud. y  dispone del Plan  Anual de Capacitacion )', '4.20.1', NULL, NULL, 1, 148),
	(150, 'Cuenta con Directorio actualizado de Agentes Comunitarios por sectores', '4.20.2', NULL, NULL, 1, 148),
	(151, 'Capacita a los Agentes  Comunitario de Salud -ACS', '4.20.3', NULL, NULL, 1, 148),
	(152, 'Realiza actividades para el desarrollo del Programa de Promoción de la Salud en Instituciones Educativas', '4.20.4', NULL, NULL, 1, 148),
	(153, 'Articula con el Municipaio acciones para mejorar o mitigar las condiciones que generan riesgo para enfermar (TBC /VIH,  Enfermedades metaxenicas y zoonoticas , anemia y Emergencias y desastres )', '4.20.5', NULL, NULL, 1, 148),
	(155, 'Cuenta con personal suficiente y capacitado para el proceso de afiliación y digitación de FUAs', '4.21.1', NULL, NULL, 1, 154),
	(156, 'Cuenta con equipamiento informatico adecuado para el registro informatico y atención SIS(ver velocidad adecuada de internet)', '4.21.2', NULL, NULL, 1, 154),
	(157, 'Cuenta con materiales e insumo suficientes para atención de asegurados y registro de información generada en la IPRESS', '4.21.3', NULL, NULL, 1, 154),
	(158, 'Se socializan e implementan medidas correctivas en relacion a las observaciones por reglas de consistencia (RC) del aplicativo ARFSIS', '4.21.4', NULL, NULL, 1, 154),
	(159, 'Cuenta con ambiente para conservación de FUAs en cajas archiveras', '4.21.5', NULL, NULL, 1, 154),
	(161, 'El EE.SS. tiene conformado su Grupo de Trabajo de Gestión de Riesgos de Desastres, formalmente constituido y operativo.', '4.22.1', NULL, NULL, 1, 160),
	(162, 'El EESS cuenta con el Plan de Gestion de Riesgo y desantre (GRD) que prioriza riesgos  pluviales', '4.22.2', NULL, NULL, 1, 160),
	(163, 'El EE.SS. Cuenta con brigadistas capacitados  y tiene Planes de Respuesta frente a Emergencias y Desastres.', '4.22.3', NULL, NULL, 1, 160),
	(164, 'El EE.SS. cuenta con inventario de recursos actualizado de indumentaria, insumos y equipos necesarios para las intervenciones.', '4.22.4', NULL, NULL, 1, 160),
	(165, 'El EE.SS. Ha sido evaluado aplicando las guias del Indice de Seguridad Hospitalaria (ISH).', '4.22.5', NULL, NULL, 1, 160),
	(166, 'El EE.SS. realiza Simulacros de Sismos e Incendios.', '4.22.6', NULL, NULL, 1, 160),
	(168, 'Farmacia tiene publicado visible la lista de precios vigente PF,DM y PS', '4.23.1', NULL, NULL, 1, 167),
	(169, 'El establecimiento tiene publicado los resultados del indicador de disponibilidad de medicamentos del mes', '4.23.2', NULL, NULL, 1, 167),
	(170, 'Recibe reporte sospecha RAM e IADM', '4.23.3', NULL, NULL, 1, 167),
	(171, 'Disponibilidad medicamentos mayor al 80%', '4.23.4', NULL, NULL, 1, 167),
	(172, 'Reporte de stock de medicamentos a los prescriptores, mínimo mensual', '4.23.5', NULL, NULL, 1, 167),
	(174, 'Cuenta con el personal certificado para TELEMEDEICINA por ENSAP', '4.24.1', NULL, NULL, 1, 173),
	(175, 'El área de telemedicina cuenta con la instalación de sus equipos y hace uso del mismo', '4.24.2', NULL, NULL, 1, 173),
	(176, 'El Establecimiento cuenta con personal capacitado en la Escuela Nacional de Salud Publica- ENSAP y otros (Diplomado de telesalud /telemedicina )', '4.24.3', NULL, NULL, 1, 173),
	(178, 'La UPS  de laboratorio,cuenta con el stock necesario de reactivos  de acuerdo a su cartera de servicios y nivel de complejidad', '4.25.1', NULL, NULL, 1, 177),
	(179, 'La UPS  de Patologia clinica cumple con las buenas practicas de almacenamiento (BPA)', '4.25.2', NULL, NULL, 1, 177),
	(180, 'La UPS de Patologia clínica cuenta areas diferenciadas (preanalitica, analítica y postanalitica)', '4.25.3', NULL, NULL, 1, 177),
	(181, 'La UPS de Patologia clínica cuenta con un Plan de mantenimiento preventivo y/o correctivo de los equipos biomedicos de Laboratorio incluyendo calibración de pipetas automaticas.', '4.25.4', NULL, NULL, 1, 177),
	(182, 'La UPS de ecografia, esta a cargo de un profesional: MEDICO Radiologo o Medico Diplomado en Ecografia.', '4.25.5', NULL, NULL, 1, 177),
	(183, 'La UPS de Ecografia, cuenta con ecografo operativo y en doble turno', '4.25.6', NULL, NULL, 1, 177),
	(184, 'La UPS de Ecografia, cuenta con insumos, gel y papel termicoopera en doble turno.', '4.25.7', NULL, NULL, 1, 177),
	(185, 'La UPS de radiologia, esta a cargo de un profesional: MEDICO Radiologo o tecnologo  Medico o tecnicoen Rayos X', '4.25.8', NULL, NULL, 1, 177),
	(186, 'La UPS de Radiologia, cuenta con equipo de Rayos X  y Procesaror de placas  operativo', '4.25.9', NULL, NULL, 1, 177),
	(187, 'La UPS de Radiologia, cuenta con insumos', '4.25.10', NULL, NULL, 1, 177),
	(188, 'La UPS de Radiologia, cuenta con doble turno de atencion', '4.25.11', NULL, NULL, 1, 177),
	(190, 'Difusión interna', '4.26.1', NULL, NULL, 1, 189),
	(191, 'Difusión externa', '4.26.2', NULL, NULL, 1, 189),
	(192, 'RECURSOS HUMANOS', '4.26.3', NULL, NULL, 1, 189);